# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors onto a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/from-1.5/blocks/source
source "azure-arm" "autogenerated_1" {
  build_resource_group_name         = "${var.build_resource_group_name}"
  client_id                         = "${var.client_id}"
  client_secret                     = "${var.client_secret}"
  communicator                      = "winrm"
  image_offer                       = "${var.image_offer}"
  image_publisher                   = "${var.image_publisher}"
  image_sku                         = "${var.image_sku}"
  image_version                     = "${var.image_version}"
  managed_image_name                = "${var.destination_image_name}"
  managed_image_resource_group_name = "${var.destination_resource_group_name}"
  os_type                           = "Windows"

  shared_image_gallery_destination {
    gallery_name        = "${var.destination_gallery_name}"
    image_name          = "${var.destination_image_name}"
    image_version       = "${var.destination_image_version}"
    replication_regions = ["${var.destination_replication_region}"]
    resource_group      = "${var.destination_resource_group_name}"
  }
  
  subscription_id = "${var.subscription_id}"
  tenant_id       = "${var.tenant_id}"
  vm_size         = "${var.vm_size}"
  winrm_insecure  = "true"
  winrm_timeout   = "3m"
  winrm_use_ssl   = "true"
  winrm_username  = "packer"
}